/* Sol & Luna GLSL, verbatim from the hero of
 * openai.com/index/introducing-gpt-6-sol-and-luna/ (chunk 1m721ga1vu-xc.js,
 * module 914469). Generated by assets/extracted/sol-luna/extract-shaders.js —
 * re-run that rather than editing here. ${...} interpolations are resolved.
 */
(function (global) {
  'use strict';
  global.SOL_SHADERS = {
    moonCrescent: `
  float moonCrescentLight(vec3 normal, vec3 light, vec3 view) {
    float side = length(light - view * dot(light, view));
    float wrap = 0.42 * smoothstep(0.15, 0.65, side);
    // An offset lighting plane keeps the inner edge a smooth elliptical arc.
    return (dot(normal, light) + wrap * (side - dot(normal, view))) / (1.0 + wrap);
  }
`,
    bodyVert: `
  varying vec3 vNormal;
  varying vec3 vLocalNormal;
  varying vec3 vLocalViewDirection;
  void main() {
    vec4 viewPosition = modelViewMatrix * vec4(position, 1.0);
    vNormal = normalize(normalMatrix * normal);
    vLocalNormal = normal;
    vLocalViewDirection = normalize(vec3(modelViewMatrix[0][2], modelViewMatrix[1][2], modelViewMatrix[2][2]));
    gl_Position = projectionMatrix * viewPosition;
  }
`,
    moonAtmosphereFrag: `
  
  float moonCrescentLight(vec3 normal, vec3 light, vec3 view) {
    float side = length(light - view * dot(light, view));
    float wrap = 0.42 * smoothstep(0.15, 0.65, side);
    // An offset lighting plane keeps the inner edge a smooth elliptical arc.
    return (dot(normal, light) + wrap * (side - dot(normal, view))) / (1.0 + wrap);
  }

  uniform float uRevealBrightness;
  uniform float uSurfaceRadius;
  varying vec3 vNormal;
  varying vec3 vLocalNormal;
  varying vec3 vLocalViewDirection;
  uniform vec3 uColor;
  uniform float uDirectional;
  uniform vec3 uLightDirection;
  void main() {
    // The hero uses an orthographic camera: every view ray is parallel.
    float facing = max(normalize(vNormal).z, 0.0);
    vec3 view = normalize(vLocalViewDirection);
    vec3 normal = normalize(vLocalNormal);
    // Light the halo from the corresponding surface point, extending its limb outward.
    vec3 projected = (normal - view * dot(normal, view)) / uSurfaceRadius;
    float radialSquared = dot(projected, projected);
    vec3 surfaceNormal = projected / max(1.0, sqrt(radialSquared))
      + view * sqrt(max(0.0, 1.0 - radialSquared));
    float lightFacing = moonCrescentLight(surfaceNormal, uLightDirection, view);
    float lightFootprint = fwidth(lightFacing) * 1.5;
    float lit = smoothstep(-0.12 - lightFootprint, 0.4 + lightFootprint, lightFacing);
    float glow = pow(facing, 3.5) * mix(1.0, lit, uDirectional);
    glow *= smoothstep(0.0, max(0.05, fwidth(facing) * 1.5), facing);
    gl_FragColor = vec4(uColor * 4.0, glow * mix(0.22, 0.65, uDirectional) * uRevealBrightness);
  }
`,
    sunRim: `
  vec3 sunRim(vec3 color, float radius, float bloomScale) {
    float edge = radius - 1.0;
    float rim = exp(-pow(edge / 0.045, 2.0))
      + exp(-pow(edge / 0.11, 2.0)) * 0.22;
    vec3 warmGold = vec3(color.r, max(color.g, color.r * 0.7), color.b);
    return mix(warmGold, vec3(1.0), 0.12) * rim * 1.25 * bloomScale;
  }
`,
    sunSurfaceFrag: `
  uniform float uRevealBrightness;
  uniform float uWhiteHeat;
  varying vec3 vNormal;
  varying vec3 vLocalNormal;
  uniform vec3 uColor;
  uniform float uBloomScale;
  uniform float uSurfaceTime;
  
  vec3 sunRim(vec3 color, float radius, float bloomScale) {
    float edge = radius - 1.0;
    float rim = exp(-pow(edge / 0.045, 2.0))
      + exp(-pow(edge / 0.11, 2.0)) * 0.22;
    vec3 warmGold = vec3(color.r, max(color.g, color.r * 0.7), color.b);
    return mix(warmGold, vec3(1.0), 0.12) * rim * 1.25 * bloomScale;
  }


  float solarHash(vec3 p) {
    p = fract(p * 0.1031);
    p += dot(p, p.yzx + 33.33);
    return fract((p.x + p.y) * p.z);
  }

  float solarNoise(vec3 p) {
    vec3 cell = floor(p);
    vec3 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    return mix(
      mix(mix(solarHash(cell), solarHash(cell + vec3(1, 0, 0)), f.x),
          mix(solarHash(cell + vec3(0, 1, 0)), solarHash(cell + vec3(1, 1, 0)), f.x), f.y),
      mix(mix(solarHash(cell + vec3(0, 0, 1)), solarHash(cell + vec3(1, 0, 1)), f.x),
          mix(solarHash(cell + vec3(0, 1, 1)), solarHash(cell + vec3(1, 1, 1)), f.x), f.y),
      f.z);
  }

  void main() {
    vec3 normal = normalize(vNormal);
    float facing = max(normal.z, 0.0);
    vec3 surface = normalize(vLocalNormal);
    // Visible convection at hero scale, with continuous rather than random motion.
    vec3 drift = vec3(0.12, 0.072, -0.096) * uSurfaceTime;
    float broad = solarNoise(surface * 5.0 + vec3(7.1, 2.8, 4.3) + drift);
    vec3 warped = surface * 15.0 + broad * 2.2 + drift.yzx * 2.0;
    float cells = solarNoise(warped);
    // Fade the finest detail when it becomes smaller than a screen pixel.
    float detailVisibility = 1.0 - smoothstep(0.5, 1.5, length(fwidth(surface * 42.0)));
    float grain = mix(0.5, solarNoise(surface * 42.0 + drift.zxy * 4.0), detailVisibility);
    float heat = smoothstep(0.15, 0.85, broad * 0.45 + cells * 0.4 + grain * 0.15);
    float colorEnergy = 1.0 - min(uColor.r, min(uColor.g, uColor.b));
    // Map temperature to orange, gold, then yellow, without adding white.
    // Keep the blue channel low so HDR bloom cannot bleach the hot patches.
    vec3 deepOrange = uColor * vec3(1.0, mix(1.0, 0.62, colorEnergy), 1.0);
    vec3 gold = vec3(uColor.r, max(uColor.g, uColor.r * 0.48), uColor.b);
    vec3 hotYellow = vec3(uColor.r, max(uColor.g, uColor.r * 0.92), uColor.b);
    vec3 surfaceColor = mix(deepOrange, gold, smoothstep(0.12, 0.58, heat));
    surfaceColor = mix(surfaceColor, hotYellow, smoothstep(0.5, 0.88, heat));
    float roundness = mix(0.5, 1.0, sqrt(facing))
      * (0.9 + 0.1 * dot(normal, normalize(vec3(-0.4, 0.5, 1.0))));
    vec3 emission = surfaceColor
      * mix(1.1, 2.2, heat) * roundness * (1.0 + colorEnergy * 0.15);
    // Feather the outer ~8% into the optical halo's color at the limb.
    // Keep the sphere opaque so it still occludes stars and masks bloom.
    vec3 limbGlow = uColor * (0.28 + 0.055) * 4.0 * uBloomScale;
    emission = mix(limbGlow, emission, smoothstep(0.0, 0.4, facing));
    emission += sunRim(uColor, sqrt(max(1.0 - facing * facing, 0.0)), uBloomScale);
    // Cool the opaque surface from white to gold while it continues to occlude stars.
    vec3 whiteHot = vec3(2.2) * mix(0.65, 1.0, sqrt(facing))
      + sunRim(vec3(1.0), sqrt(max(1.0 - facing * facing, 0.0)), uBloomScale);
    emission = mix(emission, whiteHot, uWhiteHeat);
    // Brighten the textured surface itself; keep depth and opacity stable.
    gl_FragColor = vec4(emission * uRevealBrightness, 1.0);
  }
`,
    coronaVert: `
  varying vec2 vPoint;
  void main() {
    vPoint = (uv - 0.5) * 14.0;
    vec4 viewCenter = modelViewMatrix * vec4(0.0, 0.0, 0.0, 1.0);
    vec2 scale = vec2(length(modelMatrix[0].xyz), length(modelMatrix[1].xyz));
    viewCenter.xy += position.xy * scale;
    gl_Position = projectionMatrix * viewCenter;
  }
`,
    coronaFrag: `
  uniform float uRevealBrightness;
  uniform float uWhiteHeat;
  varying vec2 vPoint;
  uniform vec3 uColor;
  uniform float uBloomScale;
  uniform float uEclipse;
  uniform float uDiamond;
  uniform float uSurfaceTime;
  uniform vec3 uMoon;
  
  vec3 sunRim(vec3 color, float radius, float bloomScale) {
    float edge = radius - 1.0;
    float rim = exp(-pow(edge / 0.045, 2.0))
      + exp(-pow(edge / 0.11, 2.0)) * 0.22;
    vec3 warmGold = vec3(color.r, max(color.g, color.r * 0.7), color.b);
    return mix(warmGold, vec3(1.0), 0.12) * rim * 1.25 * bloomScale;
  }


  vec2 coronaGradient(vec2 cell) {
    float angle = fract(sin(dot(cell, vec2(127.1, 311.7))) * 43758.5453) * 6.2831853;
    return vec2(cos(angle), sin(angle));
  }

  float coronaPerlin(vec2 point) {
    vec2 cell = floor(point);
    vec2 local = fract(point);
    vec2 fade = local * local * local * (local * (local * 6.0 - 15.0) + 10.0);
    return mix(
      mix(dot(coronaGradient(cell), local),
          dot(coronaGradient(cell + vec2(1.0, 0.0)), local - vec2(1.0, 0.0)), fade.x),
      mix(dot(coronaGradient(cell + vec2(0.0, 1.0)), local - vec2(0.0, 1.0)),
          dot(coronaGradient(cell + vec2(1.0)), local - vec2(1.0)), fade.x),
      fade.y);
  }

  void main() {
    float radius = length(vPoint);
    float outside = max(radius - 1.0, 0.0);
    // A tight rim plus a much fainter, long tail; no visible halo boundary.
    float outerHalo = exp(-outside * 1.15) * 0.055;
    float haloFade = 1.0 - smoothstep(4.5, 7.0, radius);
    float halo = (exp(-outside * 4.8) * 0.28 + outerHalo) * haloFade;
    // Cool the halo along with the sun's surface.
    vec3 glowColor = mix(uColor, vec3(1.0), uWhiteHeat);
    vec3 light = glowColor * halo * 4.0 * uBloomScale
      + sunRim(glowColor, radius, uBloomScale);
    if (uEclipse > 0.0 || uDiamond > 0.0) {
      // Direction-based noise closes around the limb without an angular seam.
      // Compress its radial domain into soft streamers, drifting on the scene clock.
      vec2 radial = vPoint / max(radius, 0.001);
      vec2 drift = vec2(0.004, -0.003) * uSurfaceTime;
      float broad = coronaPerlin(radial * 2.8 + drift);
      vec2 detailPoint = radial * (11.0 + outside * 0.8) + drift * 0.6 + 8.3;
      float detailVisibility = 1.0 - smoothstep(0.3, 0.8, length(fwidth(detailPoint)));
      float detail = coronaPerlin(detailPoint) * detailVisibility;
      float streamers = smoothstep(-0.45, 0.55, broad + detail * 0.3);
      float inner = exp(-outside * 8.0) * (0.22 + detail * 0.025);
      // Give the corona the normal bloom's reach while retaining uneven streamers.
      float wisps = outerHalo * (0.8 + streamers * 2.4);
      vec3 eclipseLight = glowColor * (inner + wisps);
      eclipseLight *= haloFade;
      light = mix(light, eclipseLight, uEclipse);

      // The final exposed sunlight sits opposite the Moon's projected center.
      vec2 direction = -uMoon.xy / max(length(uMoon.xy), 0.0001);
      vec2 diamondPoint = vPoint - direction * 1.02;
      float beadWidth = max(0.025, fwidth(radius));
      float bead = exp(-dot(diamondPoint, diamondPoint) / (beadWidth * beadWidth));
      float scatter = exp(-length(diamondPoint) * 18.0) * 0.08;
      light += glowColor * (bead * 0.8 + scatter) * uDiamond;
    }
    if (uMoon.z > 0.0) {
      float moonEdge = length(vPoint - uMoon.xy) - uMoon.z;
      float footprint = max(fwidth(moonEdge), 0.006);
      light *= smoothstep(-footprint, footprint, moonEdge);
    }
    gl_FragColor = vec4(light * uRevealBrightness, 1.0);
  }
`,
    starBuildIn: `
  uniform float uBuildIn;
  float starBuildIn(float seed) {
    float delay = seed * 0.1;
    return smoothstep(delay, delay + 0.55, uBuildIn)
      * mix(0.2, 1.0, smoothstep(0.2, 1.0, uBuildIn));
  }
`,
    spriteSupport: `
  varying float vParticleDiameter;
  #ifdef ZOOM_RUSH
    varying vec2 vRushDirection;
    varying float vRushStretch;
    varying float vRushGlow;
    varying float vSpriteDiameter;
  #endif
  vec2 astraSpritePixel(float flareExtent) {
    #ifdef ZOOM_RUSH
      return (gl_PointCoord - vec2(0.5)) * vSpriteDiameter;
    #else
      return (gl_PointCoord - vec2(0.5)) * max(vParticleDiameter * flareExtent, 4.0);
    #endif
  }
  float astraCubicCoverage(float coordinate) {
    float x = abs(coordinate);
    if (x < 1.0) return (4.0 - 6.0 * x * x + 3.0 * x * x * x) / 6.0;
    float tail = max(2.0 - x, 0.0);
    return tail * tail * tail / 6.0;
  }
  float astraFilteredCore(vec2 pixel, float area) {
    return astraCubicCoverage(pixel.x) * astraCubicCoverage(pixel.y)
      * area * vParticleDiameter * vParticleDiameter;
  }
`,
    dustFrag: `
  varying float vBrightness;
  varying float vLens;
  varying float vOpacity;
  
  varying float vParticleDiameter;
  #ifdef ZOOM_RUSH
    varying vec2 vRushDirection;
    varying float vRushStretch;
    varying float vRushGlow;
    varying float vSpriteDiameter;
  #endif
  vec2 astraSpritePixel(float flareExtent) {
    #ifdef ZOOM_RUSH
      return (gl_PointCoord - vec2(0.5)) * vSpriteDiameter;
    #else
      return (gl_PointCoord - vec2(0.5)) * max(vParticleDiameter * flareExtent, 4.0);
    #endif
  }
  float astraCubicCoverage(float coordinate) {
    float x = abs(coordinate);
    if (x < 1.0) return (4.0 - 6.0 * x * x + 3.0 * x * x * x) / 6.0;
    float tail = max(2.0 - x, 0.0);
    return tail * tail * tail / 6.0;
  }
  float astraFilteredCore(vec2 pixel, float area) {
    return astraCubicCoverage(pixel.x) * astraCubicCoverage(pixel.y)
      * area * vParticleDiameter * vParticleDiameter;
  }


  void main() {
    vec2 pixel = astraSpritePixel(1.0);
    float distanceToCenter = length(pixel) * 2.0 / max(vParticleDiameter, 0.0001);
    float disc = 1.0 - smoothstep(0.22, 1.0, distanceToCenter);
    float core = mix(astraFilteredCore(pixel, 0.256408), pow(disc, 1.5),
      smoothstep(2.0, 4.0, vParticleDiameter));
    float alpha = core * vOpacity;

    if (alpha <= 0.0) {
      discard;
    }

    gl_FragColor = vec4(vec3(vBrightness), alpha);
  }
`,
    starFrag: `
  varying float vBrightness;
  varying vec3 vColor;
  varying float vLens;
  varying float vOpacity;
  varying float vRayStrength;
  varying float vRayScale;
  varying float vGlimmerStrength;
  
  varying float vParticleDiameter;
  #ifdef ZOOM_RUSH
    varying vec2 vRushDirection;
    varying float vRushStretch;
    varying float vRushGlow;
    varying float vSpriteDiameter;
  #endif
  vec2 astraSpritePixel(float flareExtent) {
    #ifdef ZOOM_RUSH
      return (gl_PointCoord - vec2(0.5)) * vSpriteDiameter;
    #else
      return (gl_PointCoord - vec2(0.5)) * max(vParticleDiameter * flareExtent, 4.0);
    #endif
  }
  float astraCubicCoverage(float coordinate) {
    float x = abs(coordinate);
    if (x < 1.0) return (4.0 - 6.0 * x * x + 3.0 * x * x * x) / 6.0;
    float tail = max(2.0 - x, 0.0);
    return tail * tail * tail / 6.0;
  }
  float astraFilteredCore(vec2 pixel, float area) {
    return astraCubicCoverage(pixel.x) * astraCubicCoverage(pixel.y)
      * area * vParticleDiameter * vParticleDiameter;
  }


  void main() {
    float flareExtent = mix(1.0, 3.0, vGlimmerStrength);
    vec2 pixel = astraSpritePixel(flareExtent);
    vec2 point = pixel * 2.0 / max(vParticleDiameter, 0.0001);
    float distanceToCenter = length(point);
    float disc = 1.0 - smoothstep(0.08, 1.0, distanceToCenter);
    float core = pow(disc, 2.2);
    vec2 rayPoint = point / vRayScale;
    float rayFalloff = mix(28.0, 6.0, vGlimmerStrength);
    float horizontalRay = exp(-abs(rayPoint.y) * rayFalloff)
      * (1.0 - smoothstep(0.18, 1.0, abs(rayPoint.x)));
    float verticalRay = exp(-abs(rayPoint.x) * rayFalloff)
      * (1.0 - smoothstep(0.18, 1.0, abs(rayPoint.y)));
    float rays = max(horizontalRay, verticalRay)
      * mix(0.28, 0.85, vGlimmerStrength) * vRayStrength;
    float resolved = smoothstep(2.0, 4.0, vParticleDiameter);
    float alpha = mix(astraFilteredCore(pixel, 0.150904), max(core, rays), resolved)
      * vOpacity;
    #ifdef TRANSIT_STARS
      float trailAlpha = 0.0;
    #endif
    #ifdef ZOOM_RUSH
      // Extend the glow behind the star; keep its leading edge, core and flare intact.
      float along = dot(point, vRushDirection);
      float across = dot(point, vec2(-vRushDirection.y, vRushDirection.x));
      #ifndef TRANSIT_STARS
      float glowAlong = min(along, 0.0) / vRushStretch + max(along, 0.0);
      vec2 glowPoint = vec2(glowAlong, across);
      alpha += exp(-2.2 * dot(glowPoint, glowPoint)) * 0.16 * vRushGlow * vOpacity;
      #endif
      float trailLength = vRushStretch - 1.0;
      if (trailLength > 0.001) {
        float end = along - clamp(along, -trailLength, 0.0);
        float fade = 1.0 - smoothstep(0.0, trailLength, -along);
        #ifdef TRANSIT_STARS
          // A narrow light streak tapers into darkness instead of a broad comet plume.
          float width = mix(0.16, 0.5, fade);
          float crossSection = across * across / (width * width);
          float trail = exp(-crossSection - 4.0 * end * end) * 0.4
            + exp(-crossSection * 0.3 - 2.2 * end * end) * 0.05;
          trailAlpha = trail * fade * fade * vRushGlow * vOpacity;
          alpha += trailAlpha;
        #else
          alpha += exp(-4.0 * (across * across + end * end))
            * fade * 0.2 * vRushGlow * vOpacity;
        #endif
      }
    #endif

    if (alpha <= 0.0) {
      discard;
    }

    float whiteCore = mix(0.59228, core, resolved)
      * smoothstep(0.9, 2.8, vBrightness)
      * 0.82;
    float colorEnergy = 1.0
      - min(vColor.r, min(vColor.g, vColor.b));
    vec3 emission = mix(vColor, vec3(1.0), whiteCore)
      * vBrightness
      * (1.0 + colorEnergy * 0.42);
    #ifdef TRANSIT_STARS
      // Faster trails approach white while the star itself keeps its authored color.
      float whiteTrail = mix(0.35, 0.95, smoothstep(0.1, 0.8, vRushGlow));
      vec3 trailEmission = mix(vColor, vec3(1.0), whiteTrail) * vBrightness;
      emission = (emission * (alpha - trailAlpha) + trailEmission * trailAlpha) / alpha;
    #endif
    gl_FragColor = vec4(emission, alpha);
  }
`,
    backgroundVert: `
  
  uniform float uBuildIn;
  float starBuildIn(float seed) {
    float delay = seed * 0.1;
    return smoothstep(delay, delay + 0.55, uBuildIn)
      * mix(0.2, 1.0, smoothstep(0.2, 1.0, uBuildIn));
  }

  attribute vec4 star;
  attribute vec4 tint;
  uniform float uTime;
  uniform float uPixelRatio;
  uniform float uImageScale;
  uniform float uTravel;
  uniform float uHalfView;
  uniform float uPixelToField;
  varying vec3 vColor;
  varying float vOpacity;
  varying float vCoreDiameter;
  varying float vFlareDiameter;
  varying float vRasterSize;
  varying float vRayWidth;
  void main() {
    float reveal = starBuildIn(star.z / 6.28318530718);
    float scale = uPixelRatio * uImageScale * sqrt(reveal);
    float settled = smoothstep(8.3, 9.5, uTime);
    float pulse = pow(0.5 + 0.5 * sin(star.z + uTime * star.w), 3.0);
    vCoreDiameter = star.x * scale;
    vFlareDiameter = tint.w * scale * (1.0 - 0.18 * settled * pulse);
    vRasterSize = max(max(vCoreDiameter * 6.0, tint.w * scale), 4.0);
    vRayWidth = max(0.35, 0.6 * scale);
    vColor = tint.rgb;
    vOpacity = star.y * smoothstep(0.0, 0.2, reveal);
    gl_PointSize = vRasterSize;
    // Wrap beyond the full unpulsed sprite, keeping the pool fixed for this crop.
    float halfSpan = uHalfView + 0.5 * vRasterSize * uPixelToField / uPixelRatio;
    if (abs(position.x) > halfSpan) {
      gl_Position = vec4(2.0, 2.0, 2.0, 1.0);
      return;
    }
    vec3 shifted = position;
    float travel = uTravel * (4.0 + position.z);
    shifted.x = mod(position.x + travel + halfSpan, 2.0 * halfSpan) - halfSpan;
    gl_Position = projectionMatrix * modelViewMatrix * vec4(shifted, 1.0);
  }
`,
    backgroundFrag: `
  varying vec3 vColor;
  varying float vOpacity;
  varying float vCoreDiameter;
  varying float vFlareDiameter;
  varying float vRasterSize;
  varying float vRayWidth;
  float coverage(float coordinate) {
    float x = abs(coordinate);
    if (x < 1.0) return (4.0 - 6.0 * x * x + 3.0 * x * x * x) / 6.0;
    float tail = max(2.0 - x, 0.0);
    return tail * tail * tail / 6.0;
  }
  void main() {
    vec2 pixel = (gl_PointCoord - 0.5) * vRasterSize;
    float diameterSquared = vCoreDiameter * vCoreDiameter;
    // Preserve the energy of subpixel stars without blinking at pixel boundaries.
    float filtered = coverage(pixel.x) * coverage(pixel.y) * diameterSquared * 0.45;
    float disc = exp(-8.0 * dot(pixel, pixel) / max(diameterSquared, 0.0001));
    float core = mix(filtered, disc, smoothstep(2.0, 4.0, vCoreDiameter));
    float halo = exp(-3.5 * length(pixel) / max(vCoreDiameter, 0.001)) * 0.12;
    halo *= smoothstep(1.5, 3.5, vCoreDiameter);
    float rays = 0.0;
    if (vFlareDiameter > 0.0) {
      vec2 arm = max(vec2(0.0), 1.0 - abs(pixel) / (vFlareDiameter * 0.5));
      float horizontal = exp(-abs(pixel.y) / vRayWidth) * pow(arm.x, 3.0);
      float vertical = exp(-abs(pixel.x) / vRayWidth) * pow(arm.y, 3.0);
      rays = max(horizontal, vertical) * 0.8;
    }
    float alpha = max(core + halo, rays) * vOpacity;
    if (alpha <= 0.0) discard;
    gl_FragColor = vec4(mix(vColor, vec3(1.0), core * 0.4), alpha);
  }
`,
    fieldVert: `
  
  uniform float uBuildIn;
  float starBuildIn(float seed) {
    float delay = seed * 0.1;
    return smoothstep(delay, delay + 0.55, uBuildIn)
      * mix(0.2, 1.0, smoothstep(0.2, 1.0, uBuildIn));
  }

  attribute vec3 destination;
  attribute vec3 starColor;
  attribute float starBrightness;
  attribute float starOpacity;
  attribute float starScale;
  attribute float starEnvelope;
  attribute float starVisibility;
  attribute float ambientVisibility;
  attribute float galaxyRank;
  attribute float twinklePhase;
  attribute float twinkleRate;
  attribute vec4 path;
  attribute vec2 pathOffset;
  uniform float uExpansion;
  uniform float uScatter;
  uniform float uIntensity;
  uniform float uTime;
  uniform float uFlowTime;
  uniform float uGalaxyDensity;
  uniform float uViewportWidth;
  uniform float uViewportHeight;
  uniform float uRush;
  uniform float uTravelSpeed;
  uniform float uWrapOpacity;
  uniform float uFieldSpread;
  uniform float uViewHeight;
  uniform sampler2D uPaths;
  uniform float uPixelRatio;
  varying float vBrightness;
  varying vec3 vColor;
  varying float vOpacity;
  varying float vLens;
  varying float vRayStrength;
  varying float vRayScale;
  varying float vGlimmerStrength;
  varying float vParticleDiameter;
  varying vec2 vRushDirection;
  varying float vRushStretch;
  varying float vRushGlow;
  varying float vSpriteDiameter;
  vec3 samplePath(float progress) {
    float index = clamp(progress, 0.0, 1.0) * 255.0;
    float lower = floor(index);
    vec3 a = texture2D(uPaths, vec2((lower + 0.5) / 256.0, path.y)).xyz;
    vec3 b = texture2D(uPaths, vec2((min(lower + 1.0, 255.0) + 0.5) / 256.0, path.y)).xyz;
    return mix(a, b, fract(index));
  }
  void main() {
    vec3 origin = position;
    float envelope = starEnvelope;
    float visibility = starVisibility;
    if (path.z != 0.0) {
      float phase = path.x;
      #ifdef INTRO_GALAXY
        phase = fract(phase + uFlowTime * path.z);
      #endif
      float progress = phase + path.w * sin(phase * 6.28318530718) / 6.28318530718;
      vec3 tangent = samplePath(progress + 1.0 / 255.0)
        - samplePath(progress - 1.0 / 255.0);
      vec3 across = normalize(vec3(-tangent.y, tangent.x, 0.0));
      origin = samplePath(progress) + across * pathOffset.x + vec3(0.0, 0.0, pathOffset.y);
      envelope = mix(1.0, 0.14 + 0.86 * pow(max(sin(progress * 3.14159265359), 0.0), 0.68), 0.45);
      visibility = smoothstep(0.0, 0.055, progress) * (1.0 - smoothstep(0.945, 1.0, progress));
    }
    vRayStrength = smoothstep(1.45, 2.8, starBrightness);
    vRayScale = 1.0;
    vGlimmerStrength = 0.0;
    #ifdef DUST
      vBrightness = starBrightness;
      vOpacity = starOpacity * mix(visibility, 1.0, uScatter);
      vParticleDiameter = uPixelRatio * starScale;
    #else
      float twinkle = 0.86 + 0.14 * sin(twinklePhase + uTime * 0.62 * twinkleRate);
      envelope = mix(envelope, 1.0, uScatter);
      visibility = mix(visibility, 1.0, uScatter);
      float bright = smoothstep(1.35, 1.65, starBrightness);
      vBrightness = uIntensity * starBrightness * twinkle;
      vOpacity = starOpacity * visibility * (0.92 + twinkle * 0.08);
      vParticleDiameter = uPixelRatio
        * (0.35 + starScale * envelope * visibility * 3.8 * mix(0.95, 0.6, bright))
        * (0.97 + twinkle * 0.03);
    #endif
    float reveal = starBuildIn(fract(starScale * 0.61803398875));
    vOpacity *= smoothstep(0.0, 0.2, reveal);
    #ifdef INTRO_STAR
      vOpacity *= 1.0 - smoothstep(0.18, 0.4, uExpansion);
      float central = 1.0 - step(0.0001, length(origin));
      float coreSize = mix(4.5, 7.5, clamp(starScale * 0.25, 0.0, 1.0));
      vParticleDiameter = uPixelRatio * mix(coreSize, 6.0, central);
    #endif
    // Keep the same viewport-sized star population throughout the approach.
    #ifndef INTRO_STAR
    vOpacity *= ambientVisibility;
    #endif
    vParticleDiameter *= sqrt(reveal);
    vColor = starColor;
    vLens = 0.0;
    float diameter = max(vParticleDiameter, 4.0);
    vSpriteDiameter = diameter;
    vRushStretch = 1.0;
    vRushGlow = 0.0;
    #ifdef INTRO_GALAXY
      // Fly through the authored spiral toward the same focus as the bright core.
      // Virtual depth supplies perspective without changing the orthographic scene.
      vec4 galaxyFocus = viewMatrix * vec4(0.0, 1.2 * uExpansion, 0.0, 1.0);
      vec3 offset = mat3(modelMatrix) * origin;
      // Preserve the opening silhouette while giving each star its own approach speed.
      float depthSeed = fract(starScale * 0.754877666 + twinklePhase * 0.569840296);
      float startDepth = clamp(mix(7.0, 17.0, depthSeed) - offset.z * 1.5, 5.0, 19.0);
      float travelDepth = startDepth - uExpansion * 38.0;
      float approach = startDepth / max(1.5, travelDepth);
      vec4 galaxyPoint = galaxyFocus;
      galaxyPoint.xy += offset.xy * approach;
      galaxyPoint.z = -max(1.5, -galaxyFocus.z + travelDepth - 12.0);
      vOpacity = starOpacity * visibility * smoothstep(0.0, 0.2, reveal)
        * smoothstep(1.5, 5.0, travelDepth);
      #ifndef DUST
        vOpacity *= 1.0 - step(uGalaxyDensity, galaxyRank);
      #endif
      vParticleDiameter *= min(2.0, sqrt(approach));
      vSpriteDiameter = max(vParticleDiameter, 4.0);
      gl_PointSize = vSpriteDiameter;
      gl_Position = projectionMatrix * galaxyPoint;
      vec2 edge = abs(gl_Position.xy / gl_Position.w);
      vOpacity *= 1.0 - smoothstep(0.85, 1.08, max(edge.x, edge.y));
      // Fade departing arms before the measured artwork slot gives way to copy.
      float artworkBottom = 1.2 - uViewHeight * 0.5;
      vOpacity *= smoothstep(artworkBottom, artworkBottom + 0.75,
        1.2 * uExpansion + offset.y * approach);
      vRushDirection = vec2(1.0, 0.0);
      return;
    #endif
    #ifdef INTRO_STAR
      vSpriteDiameter = max(diameter, vParticleDiameter * 2.6);
      vRushStretch = 1.0;
    #endif
    gl_PointSize = vSpriteDiameter;
    // Keep the seeded direction fixed as the field approaches.
    vec2 center = vec2(0.0, 1.2);
    vec2 radial = origin.xy;
    float startRadius = length(radial);
    float endRadius = max(startRadius, length(destination.xy - center));
    vec2 direction = startRadius > 0.0001 ? radial / startRadius : vec2(0.0, 1.0);
    vec3 expanded = vec3(center + direction * endRadius, destination.z);
    // A wider horizontal volume keeps covering the viewport as it turns in depth.
    expanded.xz *= uFieldSpread;
    // Approach the settled positions directly, without morphing between star layouts.
    vec3 point = expanded;
    #ifdef INTRO_STAR
      // Turn a compact volume around a tilted axis so stars pass in front of one another.
      float orbit = uTime * 0.85;
      vec3 axis = normalize(vec3(0.3, 1.0, 0.25));
      vec3 orbitPoint = origin * cos(orbit) + cross(axis, origin) * sin(orbit)
        + axis * dot(axis, origin) * (1.0 - cos(orbit));
      // Keep the orbit compact while the growing sun covers it.
      point = orbitPoint;
      point.y += 1.2 * uExpansion;
    #endif
    vec4 world = modelMatrix * vec4(point, 1.0);
    vec4 viewPoint = viewMatrix * world;
    #ifdef FLYBY_STARS
      vec3 field = vec3(destination.x * uFieldSpread, destination.y, destination.z * uFieldSpread);
      viewPoint = viewMatrix * modelMatrix * vec4(field, 1.0);
    #endif
    vec4 focus = viewMatrix * vec4(0.0, 1.2 * uExpansion, 0.0, 1.0);
    #ifndef INTRO_STAR
      // Travel through distributed depths rather than expanding a central emitter.
      float depth = max(2.0, -viewPoint.z);
      float focusDepth = max(12.0, -focus.z);
      // Distant stars cover the edges; nearby stars travel farther during the approach.
      float distant = smoothstep(0.75, 1.1, depth / focusDepth);
      float distance = focusDepth * mix(2.8, 1.8, distant) * (1.0 - uExpansion);
      float perspective = mix(0.55 + distant * 0.3, 1.0, depth / (depth + distance));
      viewPoint.xy = focus.xy + (viewPoint.xy - focus.xy) * perspective;
      float motionRush = uRush * (1.0 - distant) * 0.1;
      #ifdef TRANSIT_STARS
        // A uniform volume keeps supplying stars across the view as we travel through it.
        float startDepth = 32.0 + destination.z * 150.0;
        // Both ends fade to zero before a star is recycled into the far volume.
        float travelDepth = 14.0 + mod(startDepth - 14.0 - uExpansion * 490.0, 168.0);
        vec2 halfView = vec2(uViewHeight * uViewportWidth / uViewportHeight, uViewHeight) * 0.65;
        // The scene camera is orthographic: project depth into screen travel explicitly.
        vec2 travelOffset = destination.xy * halfView * 110.0;
        viewPoint.xy = focus.xy + travelOffset / travelDepth;
        // Keep virtual far stars inside the scene's clip range, behind the bodies.
        viewPoint.z = -min(travelDepth, focusDepth + 1.0);
        perspective = min(2.6, 90.0 / travelDepth);
        // Short exposure trails follow projected speed, not just the reveal's brightness.
        vec2 velocity = (projectionMatrix * vec4(travelOffset, 0.0, 0.0)).xy
          * uTravelSpeed / (travelDepth * travelDepth);
        float pixelSpeed = length(velocity * vec2(uViewportWidth, uViewportHeight) * 0.5);
        motionRush = uRush * smoothstep(40.0, 600.0, pixelSpeed);
        vOpacity *= smoothstep(14.0, 60.0, travelDepth)
          * (1.0 - smoothstep(120.0, 182.0, travelDepth))
          * (1.0 - smoothstep(0.85, 1.0, uExpansion));
      #endif
      vParticleDiameter *= perspective;
      // Only nearby stars leave short exposure streaks during the fast approach.
      float rushLength = motionRush
        * (0.5 + 0.5 * fract(twinklePhase)) * float(RUSH_LENGTH) * uPixelRatio;
      // Preserve the reconstruction filter's four-pixel support even for distant stars.
      float rushDiameter = max(vParticleDiameter, 4.0);
      vSpriteDiameter = min(rushDiameter * 3.0, rushDiameter + rushLength);
      vRushStretch = vSpriteDiameter / rushDiameter;
      #ifndef DUST
        // Give the moving stars room for a halo without widening their sharp cores.
        vRushGlow = motionRush;
        vSpriteDiameter *= mix(1.0, float(RUSH_GLOW_EXTENT), vRushGlow);
        vBrightness *= 1.0 + vRushGlow * 1.2;
      #endif
      #ifdef TRANSIT_STARS
        // Reserve space behind the unchanged core for a short exposure of its motion.
        float exposureLength = min(float(TRANSIT_TRAIL_LIMIT), pixelSpeed * 0.085)
          * uRush * uPixelRatio;
        vRushStretch = 1.0 + 2.0 * exposureLength / max(vParticleDiameter, 1.0);
        vSpriteDiameter = max(vSpriteDiameter, 2.0 * exposureLength + rushDiameter * 2.0);
      #endif
      gl_PointSize = vSpriteDiameter;
    #endif
    gl_Position = projectionMatrix * viewPoint;
    #ifdef TRANSIT_STARS
      vec2 screenEdge = abs(gl_Position.xy / gl_Position.w);
      vOpacity *= 1.0 - smoothstep(0.85, 1.0, max(screenEdge.x, screenEdge.y));
    #endif
    #ifdef INTRO_STAR
      // Put the core behind the opaque bodies so the growing sun covers its glow.
      gl_Position.z = gl_Position.w * 0.999;
    #endif
    // Keep the short streaks aligned with the approach through the field.
    vec2 flight = (projectionMatrix * vec4(viewPoint.xy - focus.xy, 0.0, 0.0)).xy;
    flight *= vec2(uViewportWidth, -uViewportHeight);
    vRushDirection = length(flight) > 0.0001 ? normalize(flight) : vec2(1.0, 0.0);
    // Only the ambient field wraps sideways; passing stars recycle invisibly in depth.
    // Fade recycling back in for ambient motion and dragging after the reveal settles.
    #ifndef TRANSIT_STARS
    float halfSpan = 1.0 + gl_PointSize / (uPixelRatio * uViewportWidth);
    float screenX = gl_Position.x / gl_Position.w;
    if (abs(screenX) > halfSpan) vOpacity *= uWrapOpacity;
    gl_Position.x = (mod(screenX + halfSpan, 2.0 * halfSpan) - halfSpan) * gl_Position.w;
    #endif
  }
`,
    coreFrag: `
  uniform float uTime;
  varying float vParticleDiameter;
  varying float vSpriteDiameter;
  varying float vOpacity;
  void main() {
    vec2 pixel = (gl_PointCoord - 0.5) * vSpriteDiameter;
    float coreDiameter = vParticleDiameter * 0.55;
    float core = exp(-8.0 * dot(pixel, pixel) / max(coreDiameter * coreDiameter, 0.0001));
    float halo = exp(-3.5 * length(pixel) / max(coreDiameter, 0.001)) * 0.16;
    float alpha = (core + halo) * vOpacity;
    if (alpha <= 0.0) discard;
    float charge = smoothstep(0.1, 0.43, uTime);
    gl_FragColor = vec4(vec3(mix(0.12, 2.0, charge)), alpha);
  }
`,
  };
})(window);
